name: Continuous Integration
on:
  push:
    branches:
      - master
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.1
      - name: Install and Build
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
          git config --global user.emal
          git config --global user.name
          echo $GITHUB_TOKEN
          npm run deploy-storybook
#        uses: JamesIves/github-pages-deploy-action@3.5.7
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: dist-storybook
  publish-pkg:
    needs: deploy-storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@cade-tecnologia'
      - run: yarn install
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: yarn version --patch
      - run: git push --tags && git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
